//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveSyncDevice
    {
        public string MailboxName { get; set; }
        public string DeviceID { get; set; }
        public string DeviceType { get; set; }
        public string DeviceFriendlyName { get; set; }
        public string DeviceOS { get; set; }
        public string DeviceModel { get; set; }
        public string DeviceUserAgent { get; set; }
        public Nullable<System.DateTime> LastSuccessSyncDate { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    }
}
