//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdDiscoveredDevice
    {
        public System.Guid DeviceNumber { get; set; }
        public string Cn { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public string DistinguishedName { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
        public Nullable<System.DateTime> LastLogonTimestamp { get; set; }
        public Nullable<int> LocaleId { get; set; }
        public Nullable<int> MachineRole { get; set; }
        public string NetBiosName { get; set; }
        public Nullable<System.Guid> NetBootGuid { get; set; }
        public Nullable<System.Guid> ObjectGuid { get; set; }
        public string PhysicalLocationObject { get; set; }
        public Nullable<System.DateTime> PwdLastSet { get; set; }
        public string ObjectSid { get; set; }
        public string SAMAccountName { get; set; }
        public Nullable<System.Guid> SiteGUiD { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string UserPrincipalName { get; set; }
        public Nullable<int> UserAccountControl { get; set; }
        public Nullable<System.DateTime> WhenChanged { get; set; }
        public Nullable<System.DateTime> WhenCreated { get; set; }
        public int IsDisabled { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
