//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdElcFolder
    {
        public System.Guid ObjectGuid { get; set; }
        public string ObjectClass { get; set; }
        public string DistinguishedName { get; set; }
        public Nullable<long> DnHashID { get; set; }
        public Nullable<int> MsExchElcFolderType { get; set; }
        public string MsExchElcFolderBL { get; set; }
        public string MsExchElcFolderName { get; set; }
        public string MsExchElcFolderNameLocalized { get; set; }
        public string MsExchElcAdminDescriptionLocalized { get; set; }
        public Nullable<int> MsExchElcFlags { get; set; }
        public Nullable<int> MsExchElcFolderQuota { get; set; }
        public Nullable<long> MsExchVersion { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    }
}
