//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdForestDomain
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid ObjectGuid { get; set; }
        public string DnsRoot { get; set; }
        public string NCName { get; set; }
        public string NETBIOsName { get; set; }
        public string TrustParent { get; set; }
        public Nullable<int> MsDSBehaviorVersion { get; set; }
        public Nullable<int> SystemFlags { get; set; }
        public Nullable<int> NTMixedDomain { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    }
}
