//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdMailboxItem
    {
        public System.Guid ObjectGuid { get; set; }
        public string ObjectClass { get; set; }
        public string DistinguishedName { get; set; }
        public Nullable<long> DnHashID { get; set; }
        public string SAMAccountName { get; set; }
        public Nullable<int> SAMAccountType { get; set; }
        public string NetBIOsDomain { get; set; }
        public Nullable<int> SystemFlags { get; set; }
        public string Mail { get; set; }
        public Nullable<int> MsExchUMEnabledFlags { get; set; }
        public string HomeMDB { get; set; }
        public Nullable<long> HomeMDBHashID { get; set; }
        public string MsExchMobileMailboxPolicyLink { get; set; }
        public Nullable<long> MsExchMobileMailboxPolicyLinkHashID { get; set; }
        public string MemberOf { get; set; }
        public string MemberOfHashList { get; set; }
        public string Member { get; set; }
        public string MemberHashList { get; set; }
        public string MsExchHomeServerName { get; set; }
        public string MsExchMailboxTemplateLink { get; set; }
        public Nullable<long> MsExchMailboxTemplateLinkHashID { get; set; }
        public Nullable<int> MsExchRecipientDisplayType { get; set; }
        public string MsDSPrincipalName { get; set; }
        public string UserPrincipalName { get; set; }
        public Nullable<long> MsExchVersion { get; set; }
        public Nullable<bool> UsesActiveSync { get; set; }
        public Nullable<bool> UsesManagedFolders { get; set; }
        public Nullable<bool> UsesUnifiedMessaging { get; set; }
        public Nullable<bool> UsesJournaling { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<bool> OWAEnabled { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<System.Guid> DeviceNumber { get; set; }
    }
}
