//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdServer
    {
        public System.Guid ObjectGuid { get; set; }
        public string ObjectClass { get; set; }
        public string DistinguishedName { get; set; }
        public Nullable<long> DnHashID { get; set; }
        public string Name { get; set; }
        public string DNSHostName { get; set; }
        public Nullable<int> MsExchCurrentServerRoles { get; set; }
        public string MsExchProductID { get; set; }
        public Nullable<int> MsExchProvisioningFlags { get; set; }
        public Nullable<int> MsExchServerRole { get; set; }
        public Nullable<int> ServerRole { get; set; }
        public string NetworkAddress { get; set; }
        public string SerialNumber { get; set; }
        public string Type { get; set; }
        public Nullable<byte> DecodedServerType { get; set; }
        public Nullable<byte> DecodedSetupType { get; set; }
        public int Enterprise { get; set; }
        public Nullable<long> MsExchVersion { get; set; }
        public string ParsedDNSHostName { get; set; }
        public string MergedVersionNumber { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    }
}
