//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConfigDbSelection
    {
        public System.Guid AppId { get; set; }
        public System.Guid DeviceNumber { get; set; }
        public string Instance { get; set; }
        public string DbName { get; set; }
    
        public virtual AppConfig AppConfig { get; set; }
    }
}
