//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentSummary
    {
        public string ScenarioName { get; set; }
        public Nullable<double> PercentTotalReady { get; set; }
        public Nullable<int> TotalReady { get; set; }
        public Nullable<int> ReadyBefore { get; set; }
        public Nullable<int> ReadyAfter { get; set; }
        public Nullable<int> NotReady { get; set; }
        public Nullable<int> InsufficientData { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
