//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public System.Guid DeviceNumber { get; set; }
        public string MobRef { get; set; }
        public int MigrationRecommendation { get; set; }
        public string MigrationRecommendationDetails { get; set; }
        public Nullable<int> MvmcMigrationRecommendation { get; set; }
        public string MvmcMigrationRecommendationDetails { get; set; }
    
        public virtual Guest1 Guest1 { get; set; }
    }
}
