//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrowserExtension
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid ExtensionGuid { get; set; }
        public Nullable<System.Guid> BandClsid { get; set; }
        public string ButtonText { get; set; }
        public Nullable<System.Guid> CLSID { get; set; }
        public Nullable<System.Guid> ClsidExtension { get; set; }
        public string MenuText { get; set; }
        public Nullable<System.Guid> ControlGuid { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
