//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategorizedDevice
    {
        public System.Guid DeviceNumber { get; set; }
        public Nullable<bool> IsCategorized { get; set; }
        public Nullable<bool> IsInventorySuccessful { get; set; }
        public Nullable<byte> OsTypeId { get; set; }
        public Nullable<byte> OsVersionId { get; set; }
        public Nullable<byte> OsSkuFamily { get; set; }
        public Nullable<byte> OsSkuLevel { get; set; }
        public Nullable<bool> OsSkuIsCore { get; set; }
        public Nullable<bool> OsSkuIsN { get; set; }
        public Nullable<bool> OsSkuIsEvaluation { get; set; }
        public Nullable<byte> OsServicePack { get; set; }
        public Nullable<bool> IsRunningWindowsClient { get; set; }
        public Nullable<bool> IsRunningWindowsServer { get; set; }
        public Nullable<bool> IsRunningUnknownWindows { get; set; }
        public Nullable<bool> IsRunningWindows { get; set; }
        public Nullable<bool> IsRunningXP { get; set; }
        public Nullable<bool> IsRunningVista { get; set; }
        public Nullable<bool> IsRunningWindows7 { get; set; }
        public Nullable<bool> IsRunningWindows8 { get; set; }
        public Nullable<bool> IsRunningWindows81 { get; set; }
        public Nullable<bool> IsRunningWindows10 { get; set; }
        public Nullable<bool> IsRunningW2000 { get; set; }
        public Nullable<bool> IsRunningWin7ThinPC { get; set; }
        public Nullable<bool> IsRunningWS2003 { get; set; }
        public Nullable<bool> IsRunningWS2003R2 { get; set; }
        public Nullable<bool> IsRunningWS2008 { get; set; }
        public Nullable<bool> IsRunningWS2008R2 { get; set; }
        public Nullable<bool> IsRunningWS2012 { get; set; }
        public Nullable<bool> IsRunningWS2012R2 { get; set; }
        public Nullable<bool> IsRunningHyperVS2008 { get; set; }
        public Nullable<bool> IsRunningHyperVS2008R2 { get; set; }
        public Nullable<bool> IsRunningHyperVS2012 { get; set; }
        public Nullable<bool> IsRunningUnix { get; set; }
        public Nullable<bool> IsRunningHpux { get; set; }
        public Nullable<bool> IsRunningLinux { get; set; }
        public Nullable<bool> IsRunningVistaOrHigher { get; set; }
        public Nullable<bool> IsRunningXpOrHigher { get; set; }
        public Nullable<bool> IsPhysical { get; set; }
        public Nullable<bool> IsVirtual { get; set; }
        public Nullable<bool> IsUnknownPhysicalVirtual { get; set; }
        public Nullable<bool> IsItaniumMachine { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
