//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectorClassStatu
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid CollectorClassGuid { get; set; }
        public int CollectorClassType { get; set; }
        public int NumInstancesCollected { get; set; }
        public int CollectionTimeMs { get; set; }
        public int PersistenceTimeMs { get; set; }
        public int Status { get; set; }
        public Nullable<byte> CollectionAttempts { get; set; }
        public string ErrorMsg { get; set; }
        public string Exception { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
