//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid ControlGuid { get; set; }
        public Nullable<bool> IsBho { get; set; }
        public Nullable<bool> IsExplorerBar { get; set; }
        public Nullable<bool> IsToolbar { get; set; }
        public string FriendlyName { get; set; }
        public string Version { get; set; }
        public string ControlExe { get; set; }
        public Nullable<System.Guid> TreatAsGuid { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
