//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBaseServerProperty
    {
        public System.Guid DeviceNumber { get; set; }
        public string ServerName { get; set; }
        public string InstanceName { get; set; }
        public string MachineName { get; set; }
        public string ComputerNetbios { get; set; }
        public string ClrVersion { get; set; }
        public string Collation { get; set; }
        public Nullable<long> CollationId { get; set; }
        public Nullable<long> ComparisonStyle { get; set; }
        public string Edition { get; set; }
        public Nullable<long> EditionId { get; set; }
        public Nullable<int> EngineEdition { get; set; }
        public Nullable<byte> IsClustered { get; set; }
        public Nullable<byte> IsFulltextInstalled { get; set; }
        public Nullable<byte> IsIntegratedsecurity { get; set; }
        public Nullable<byte> IsSingleUser { get; set; }
        public Nullable<int> Lcid { get; set; }
        public string LicenseType { get; set; }
        public Nullable<int> NumLicenses { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public string ProductVersion { get; set; }
        public string ProductLevel { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string ResourceVersion { get; set; }
        public Nullable<int> SqlCharset { get; set; }
        public string SqlCharsetName { get; set; }
        public Nullable<int> SqlSortorder { get; set; }
        public string FsSharename { get; set; }
        public Nullable<int> FsEffectivelevel { get; set; }
        public Nullable<int> FsConfiguredlevel { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
