//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBaseFileGroup
    {
        public System.Guid DeviceNumber { get; set; }
        public string ServerName { get; set; }
        public string DbName { get; set; }
        public byte Fileid { get; set; }
        public string Name { get; set; }
        public string Filename { get; set; }
        public string Filegroup { get; set; }
        public string Size { get; set; }
        public string Maxsize { get; set; }
        public string Growth { get; set; }
        public string Usage { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
