//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBaseServerConfiguration
    {
        public System.Guid DeviceNumber { get; set; }
        public string ServerName { get; set; }
        public int ConfigurationId { get; set; }
        public string Name { get; set; }
        public Nullable<long> Value { get; set; }
        public Nullable<long> MinValue { get; set; }
        public Nullable<long> MaxValue { get; set; }
        public string Description { get; set; }
        public Nullable<byte> IsDynamic { get; set; }
        public Nullable<byte> IsAdvanced { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
