//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceInventoryStat
    {
        public System.Guid DeviceNumber { get; set; }
        public System.DateTime StartTime { get; set; }
        public int ElapsedTimeMs { get; set; }
        public int NumInstancesCollected { get; set; }
        public int CollectionTimeMs { get; set; }
        public int DbConnectWaitMs { get; set; }
        public int PersistenceTimeMs { get; set; }
        public bool NeedToRetryInventory { get; set; }
        public bool DiscoveredOnThisRun { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
