//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceAssessment
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid Uid { get; set; }
        public Nullable<long> DeviceHash { get; set; }
        public Nullable<byte> DeviceAssessment1 { get; set; }
        public Nullable<byte> ServerDeviceAssessment { get; set; }
        public Nullable<byte> Win7DeviceAssessment { get; set; }
        public Nullable<int> Win7OCASID { get; set; }
        public Nullable<byte> Win2K8R2DeviceAssessment { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
