//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiskDrive
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid Uid { get; set; }
        public Nullable<long> BytesPerSector { get; set; }
        public string Capabilities { get; set; }
        public string CapabilityDescriptions { get; set; }
        public string Caption { get; set; }
        public string CompressionMethod { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<long> DefaultBlockSize { get; set; }
        public string Description { get; set; }
        public string DeviceId { get; set; }
        public Nullable<long> IndexId { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public string InterfaceType { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<long> MaxBlockSize { get; set; }
        public Nullable<long> MaxMediaSize { get; set; }
        public Nullable<byte> MediaLoaded { get; set; }
        public string MediaType { get; set; }
        public Nullable<long> MinBlockSize { get; set; }
        public string Model { get; set; }
        public string Name { get; set; }
        public Nullable<long> NumberOfMediaSupported { get; set; }
        public Nullable<long> Partitions { get; set; }
        public string PnpDeviceId { get; set; }
        public Nullable<long> ScsiBus { get; set; }
        public Nullable<int> ScsiLogicalUnit { get; set; }
        public Nullable<int> ScsiPort { get; set; }
        public Nullable<int> ScsiTargetId { get; set; }
        public Nullable<long> SectorsPerTrack { get; set; }
        public Nullable<long> Signature { get; set; }
        public Nullable<long> Size { get; set; }
        public Nullable<long> TotalCylinders { get; set; }
        public Nullable<long> TotalHeads { get; set; }
        public Nullable<long> TotalSectors { get; set; }
        public Nullable<long> TotalTracks { get; set; }
        public Nullable<long> TracksPerCylinder { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
