//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filesystem
    {
        public System.Guid DeviceNumber { get; set; }
        public string Filesystem1 { get; set; }
        public Nullable<long> C1kbBlocks { get; set; }
        public Nullable<long> BlocksUsed { get; set; }
        public Nullable<long> BlocksAvailable { get; set; }
        public Nullable<int> PercentUsed { get; set; }
        public string MountPoint { get; set; }
        public string Type { get; set; }
        public string Mode { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
