//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestMetric
    {
        public System.Guid ResultId { get; set; }
        public System.Guid DeviceNumber { get; set; }
        public string MetricName { get; set; }
        public Nullable<double> OriginalValue { get; set; }
        public Nullable<double> PlacedValue { get; set; }
        public Nullable<int> PlacementStatus { get; set; }
    
        public virtual Result Result { get; set; }
    }
}
