//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest()
        {
            this.HostGuests = new HashSet<HostGuest>();
        }
    
        public System.Guid ResultId { get; set; }
        public System.Guid DeviceNumber { get; set; }
        public string VmCategory { get; set; }
        public Nullable<int> VmCount { get; set; }
        public Nullable<int> PlacementStatus { get; set; }
    
        public virtual Result Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostGuest> HostGuests { get; set; }
    }
}
