//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwareInventoryCore
    {
        public System.Guid DeviceNumber { get; set; }
        public string ComputerName { get; set; }
        public string OsFamilyName { get; set; }
        public string CurrentOperatingSystem { get; set; }
        public string OsServicePack { get; set; }
        public Nullable<byte> OsArchitectureBits { get; set; }
        public Nullable<byte> CpuArchitectureBits { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
