//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwareInventoryEx
    {
        public System.Guid DeviceNumber { get; set; }
        public string WMIStatus { get; set; }
        public string SSHStatus { get; set; }
        public string ComputerModel { get; set; }
        public string ActiveNetworkAdapter { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string DNSServer { get; set; }
        public string SubnetMask { get; set; }
        public string IPGateway { get; set; }
        public string WINSServer { get; set; }
        public string RegisteredUserName { get; set; }
        public string Domain_Workgroup { get; set; }
        public string DaysSinceDomainAccountUpdate { get; set; }
        public string NumberOfProcessors { get; set; }
        public string NumberOfCores { get; set; }
        public string NumberOfLogicalProcessors { get; set; }
        public string Cpu { get; set; }
        public string SystemMemory { get; set; }
        public string VideoCard { get; set; }
        public string VideoCardMemory { get; set; }
        public string SoundCard { get; set; }
        public string DiskDrive { get; set; }
        public string DiskDriveSize { get; set; }
        public string OpticalDrive { get; set; }
        public string BIOs { get; set; }
        public string BIOsSerialNumber { get; set; }
        public string BIOsManufacturer { get; set; }
        public Nullable<System.DateTime> BIOsReleaseDate { get; set; }
        public string MachineType { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
