//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwareAssessment
    {
        public System.Guid DeviceNumber { get; set; }
        public Nullable<byte> AggregateAssessment { get; set; }
        public Nullable<byte> AggregateUpgradeability { get; set; }
        public Nullable<byte> AudioAssessment { get; set; }
        public Nullable<byte> AudioUpgradeToCapable { get; set; }
        public Nullable<byte> AudioUpgradeToPremium { get; set; }
        public Nullable<byte> BiosAssessment { get; set; }
        public Nullable<byte> ChassisDescription { get; set; }
        public string ComputerSystemName { get; set; }
        public Nullable<byte> CpuAssessment { get; set; }
        public Nullable<byte> CpuAddressWidth { get; set; }
        public Nullable<byte> GraphicsAssessment { get; set; }
        public Nullable<long> AdapterRamMax { get; set; }
        public Nullable<byte> GraphicsUpgradeToCapable { get; set; }
        public Nullable<byte> GraphicsUpgradeToPremium { get; set; }
        public Nullable<byte> HarddiskAssessment { get; set; }
        public Nullable<byte> HarddiskFreeSpace { get; set; }
        public Nullable<long> HarddiskFreeSpaceMax { get; set; }
        public Nullable<byte> HarddiskFreeUpgradeToCapable { get; set; }
        public Nullable<byte> HarddiskFreeUpgradeToPremium { get; set; }
        public Nullable<byte> HarddiskTotalSize { get; set; }
        public Nullable<long> HarddiskTotalSizeSum { get; set; }
        public Nullable<byte> HarddiskTotalUpgradeToCapable { get; set; }
        public Nullable<byte> HarddiskTotalUpgradeToPremium { get; set; }
        public Nullable<byte> HarddiskUpgradeToCapable { get; set; }
        public Nullable<byte> HarddiskUpgradeToPremium { get; set; }
        public Nullable<long> TotalPhysicalMemory { get; set; }
        public Nullable<byte> MemoryAssessment { get; set; }
        public Nullable<byte> MemoryUpgradeToCapable { get; set; }
        public Nullable<byte> MemoryUpgradeToPremium { get; set; }
        public string NetworkId { get; set; }
        public Nullable<byte> OpticaldiskAssessment { get; set; }
        public Nullable<byte> OpticaldiskUpgradeToCapable { get; set; }
        public Nullable<byte> OpticaldiskUpgradeToPremium { get; set; }
        public Nullable<int> ProductType { get; set; }
        public string ReasonAggregateAssessment { get; set; }
        public string ReasonAggregateUpgradeability { get; set; }
        public Nullable<System.Guid> HostDeviceNumber { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
