//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostMetric
    {
        public System.Guid ResultId { get; set; }
        public System.Guid HostNumber { get; set; }
        public string MetricName { get; set; }
        public Nullable<double> Capacity { get; set; }
        public Nullable<double> Reserve { get; set; }
        public Nullable<double> GuestUtilization { get; set; }
        public Nullable<int> OverflowStatus { get; set; }
        public Nullable<double> TotalUtilization { get; set; }
    
        public virtual Result Result { get; set; }
    }
}
