//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostGuestDetail
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid Uid { get; set; }
        public string DnsHostName { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string GuestSystemName { get; set; }
        public string GuestName { get; set; }
        public Nullable<int> GuestOperationalStatus { get; set; }
        public Nullable<int> GuestEnabledDefault { get; set; }
        public Nullable<int> GuestUpTime { get; set; }
        public string GuestIntrinsicExchangeItems { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string GuestDnsHostName { get; set; }
        public string GuestOsName { get; set; }
        public string GuestOsVersion { get; set; }
        public string GuestOsServicePack { get; set; }
        public string GuestOsBuildNumber { get; set; }
        public Nullable<int> GuestServicePackMajor { get; set; }
        public Nullable<int> GuestServicePackMinor { get; set; }
        public Nullable<int> GuestProductType { get; set; }
        public Nullable<int> GuestOsProductSuite { get; set; }
        public Nullable<System.Guid> GuestDeviceNumber { get; set; }
        public Nullable<int> GuestEnabledState { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
