//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class IISVirtualDirApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IISVirtualDirApplication()
        {
            this.AppConfigs = new HashSet<AppConfig>();
        }
    
        public System.Guid DeviceNumber { get; set; }
        public string Name { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string AppRoot { get; set; }
        public string Path { get; set; }
        public string AppPoolId { get; set; }
        public Nullable<bool> HasAspx { get; set; }
        public Nullable<bool> HasAsp { get; set; }
        public Nullable<bool> HasPhp { get; set; }
        public Nullable<bool> HasHtml { get; set; }
        public Nullable<bool> HasJava { get; set; }
        public Nullable<bool> HasRuby { get; set; }
    
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppConfig> AppConfigs { get; set; }
    }
}
