//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Infra()
        {
            this.InfraHosts = new HashSet<InfraHost>();
            this.InfraMetrics = new HashSet<InfraMetric>();
        }
    
        public System.Guid ResultId { get; set; }
        public System.Guid InfraNumber { get; set; }
        public string InfraName { get; set; }
        public Nullable<int> OverflowStatus { get; set; }
    
        public virtual Result Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfraHost> InfraHosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfraMetric> InfraMetrics { get; set; }
    }
}
