//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfraConfig
    {
        public System.Guid ConfigGuid { get; set; }
        public string ScenarioName { get; set; }
        public string Config { get; set; }
        public Nullable<System.DateTime> ConfigDate { get; set; }
    }
}
