//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class instance
    {
        public string schema_version { get; set; }
        public System.DateTime install_date { get; set; }
        public string description { get; set; }
        public Nullable<bool> inventory_data_assessed { get; set; }
        public Nullable<bool> perf_data_assessed { get; set; }
        public string culture_info { get; set; }
        public Nullable<System.DateTime> last_sqm_upload_time { get; set; }
        public bool is_sample_db { get; set; }
    }
}
