//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory1
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid Uid { get; set; }
        public Nullable<int> Clustered { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string DnsHostName { get; set; }
        public string Instanceid { get; set; }
        public Nullable<byte> Iswow64 { get; set; }
        public Nullable<long> Language { get; set; }
        public string Servicename { get; set; }
        public Nullable<long> Sku { get; set; }
        public string Skuname { get; set; }
        public Nullable<int> Splevel { get; set; }
        public Nullable<int> Sqlservicetype { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string Version { get; set; }
        public string Fileversion { get; set; }
        public string Vsname { get; set; }
        public string Checksum { get; set; }
        public string InstanceName { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
