//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicensingAssessment
    {
        public System.Guid DeviceNumber { get; set; }
        public byte LicenseType { get; set; }
        public byte LicenseAssessment { get; set; }
        public byte SlicTableStatus { get; set; }
        public byte MsdmTablePresent { get; set; }
        public byte OemInstalledEdition { get; set; }
        public byte Reason { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
