//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogicalDisk
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid Uid { get; set; }
        public Nullable<int> Access { get; set; }
        public Nullable<long> BlockSize { get; set; }
        public string Caption { get; set; }
        public Nullable<byte> Compressed { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string Description { get; set; }
        public string DeviceId { get; set; }
        public Nullable<long> DriveType { get; set; }
        public string FileSystem { get; set; }
        public Nullable<long> FreeSpace { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<long> MaximumComponentLength { get; set; }
        public Nullable<long> MediaType { get; set; }
        public string Name { get; set; }
        public Nullable<long> NumberOfBlocks { get; set; }
        public string PnpDeviceId { get; set; }
        public string ProviderName { get; set; }
        public string Purpose { get; set; }
        public Nullable<byte> QuotasDisabled { get; set; }
        public Nullable<byte> QuotasIncomplete { get; set; }
        public Nullable<byte> QuotasRebuilding { get; set; }
        public Nullable<long> Size { get; set; }
        public string SupportsDiskQuotas { get; set; }
        public Nullable<byte> SupportsFileBasedCompression { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<byte> VolumeDirty { get; set; }
        public string VolumeName { get; set; }
        public string VolumeSerialNumber { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
