//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemoryInfo
    {
        public System.Guid DeviceNumber { get; set; }
        public Nullable<int> MemTotalKb { get; set; }
        public Nullable<int> MemFreeKb { get; set; }
        public Nullable<int> BuffersKb { get; set; }
        public Nullable<int> CachedKb { get; set; }
        public Nullable<int> SwapCachedKb { get; set; }
        public Nullable<int> ActiveKb { get; set; }
        public Nullable<int> InactiveKb { get; set; }
        public Nullable<int> SwapTotalKb { get; set; }
        public Nullable<int> SwapFreeKb { get; set; }
        public Nullable<long> VmAllocTotalKb { get; set; }
        public Nullable<long> VmAllocUsedKb { get; set; }
        public Nullable<long> VmAllocChunkKb { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
