//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricAggregation
    {
        public System.Guid DeviceNumber { get; set; }
        public byte MetricType { get; set; }
        public Nullable<int> DataCount { get; set; }
        public Nullable<double> MetricMax { get; set; }
        public Nullable<double> MetricMin { get; set; }
        public Nullable<double> MetricAvg { get; set; }
        public Nullable<double> MetricPercentile { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
