//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricPerTimeInterval
    {
        public System.Guid DeviceNumber { get; set; }
        public byte MetricType { get; set; }
        public int TimeInterval { get; set; }
        public Nullable<double> Metric { get; set; }
        public short Runlength { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual TimeInterval TimeInterval1 { get; set; }
    }
}
