//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSClusterNode
    {
        public System.Guid DeviceNumber { get; set; }
        public string Name { get; set; }
        public Nullable<long> BuildNumber { get; set; }
        public string Caption { get; set; }
        public Nullable<long> Characteristics { get; set; }
        public string CreationClassName { get; set; }
        public string CSDVersion { get; set; }
        public string Dedicated { get; set; }
        public string Description { get; set; }
        public Nullable<long> Flags { get; set; }
        public string IdentifyingDescriptions { get; set; }
        public string InitialLoadInfo { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public string LastLoadInfo { get; set; }
        public Nullable<long> MajorVersion { get; set; }
        public Nullable<long> MinorVersion { get; set; }
        public string NameFormat { get; set; }
        public Nullable<long> NodeHighestVersion { get; set; }
        public string NodeInstanceID { get; set; }
        public Nullable<long> NodeLowestVersion { get; set; }
        public string OtherIdentifyingInfo { get; set; }
        public string PowerManagementCapabilities { get; set; }
        public Nullable<bool> PowerManagementSupported { get; set; }
        public Nullable<int> PowerState { get; set; }
        public string PrimaryOwnerContact { get; set; }
        public string PrimaryOwnerName { get; set; }
        public Nullable<int> ResetCapability { get; set; }
        public string Roles { get; set; }
        public Nullable<long> State { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
