//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSClusterService
    {
        public System.Guid DeviceNumber { get; set; }
        public string Name { get; set; }
        public string SystemName { get; set; }
        public string Caption { get; set; }
        public string CreationClassName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<long> NodeHighestVersion { get; set; }
        public Nullable<long> NodeLowestVersion { get; set; }
        public Nullable<bool> Started { get; set; }
        public string StartMode { get; set; }
        public string State { get; set; }
        public string Status { get; set; }
        public string SystemCreationClassName { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
