//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSClusterResourceGroup
    {
        public System.Guid DeviceNumber { get; set; }
        public string Name { get; set; }
        public string AntiAffinityClassNames { get; set; }
        public Nullable<long> AutoFailbackType { get; set; }
        public string Caption { get; set; }
        public Nullable<long> Characteristics { get; set; }
        public Nullable<long> DefaultOwner { get; set; }
        public string Description { get; set; }
        public Nullable<int> FailbackWindowEnd { get; set; }
        public Nullable<int> FailbackWindowStart { get; set; }
        public Nullable<long> FailoverPeriod { get; set; }
        public Nullable<long> FailoverThreshold { get; set; }
        public Nullable<long> Flags { get; set; }
        public Nullable<long> GroupType { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<bool> PersistentState { get; set; }
        public Nullable<long> Priority { get; set; }
        public Nullable<long> State { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
