//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSClusterResource
    {
        public System.Guid DeviceNumber { get; set; }
        public string Name { get; set; }
        public string Caption { get; set; }
        public Nullable<long> Characteristics { get; set; }
        public Nullable<bool> CoreResource { get; set; }
        public string CryptoCheckpoints { get; set; }
        public Nullable<long> DeadlockTimeout { get; set; }
        public Nullable<bool> DeleteRequiresAllNodes { get; set; }
        public string Description { get; set; }
        public Nullable<long> Flags { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<long> IsAlivePollInterval { get; set; }
        public Nullable<bool> IsClusterSharedVolume { get; set; }
        public Nullable<long> LooksAlivePollInterval { get; set; }
        public Nullable<long> MonitorProcessId { get; set; }
        public Nullable<long> PendingTimeout { get; set; }
        public Nullable<bool> PersistentState { get; set; }
        public Nullable<bool> QuorumCapable { get; set; }
        public string RegistryCheckpoints { get; set; }
        public Nullable<long> ResourceClass { get; set; }
        public string ResourceSpecificStatus { get; set; }
        public Nullable<long> RestartAction { get; set; }
        public Nullable<long> RestartDelay { get; set; }
        public Nullable<long> RestartPeriod { get; set; }
        public Nullable<long> RestartThreshold { get; set; }
        public Nullable<long> RetryPeriodOnFailure { get; set; }
        public Nullable<bool> SeparateMonitor { get; set; }
        public Nullable<long> State { get; set; }
        public string Status { get; set; }
        public Nullable<long> Subclass { get; set; }
        public string Type { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
