//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSClusterNetworkInterface
    {
        public System.Guid DeviceNumber { get; set; }
        public string DeviceID { get; set; }
        public string SystemName { get; set; }
        public string Adapter { get; set; }
        public string AdapterId { get; set; }
        public string Address { get; set; }
        public Nullable<int> Availability { get; set; }
        public string Caption { get; set; }
        public Nullable<long> Characteristics { get; set; }
        public string CreationClassName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> DhcpEnabled { get; set; }
        public Nullable<bool> ErrorCleared { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<long> Flags { get; set; }
        public string IdentifyingDescriptions { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public string IPv4Addresses { get; set; }
        public string IPv6Addresses { get; set; }
        public Nullable<long> LastErrorCode { get; set; }
        public string Name { get; set; }
        public string Network { get; set; }
        public string Node { get; set; }
        public string OtherIdentifyingInfo { get; set; }
        public string PowerManagementCapabilities { get; set; }
        public Nullable<bool> PowerManagementSupported { get; set; }
        public Nullable<long> PowerOnHours { get; set; }
        public Nullable<long> State { get; set; }
        public string Status { get; set; }
        public Nullable<int> StatusInfo { get; set; }
        public string SystemCreationClassName { get; set; }
        public Nullable<long> TotalPowerOnHours { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
