//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSClusterCluster
    {
        public System.Guid DeviceNumber { get; set; }
        public string Name { get; set; }
        public Nullable<long> AddEvictDelay { get; set; }
        public Nullable<long> BackupInProgress { get; set; }
        public string Caption { get; set; }
        public Nullable<long> ClusSvcHangTimeout { get; set; }
        public Nullable<long> ClusSvcRegroupOpeningTimeout { get; set; }
        public Nullable<long> ClusSvcRegroupPruningTimeout { get; set; }
        public Nullable<long> ClusSvcRegroupStageTimeout { get; set; }
        public Nullable<long> ClusSvcRegroupTickInMilliseconds { get; set; }
        public Nullable<long> ClusterGroupWaitDelay { get; set; }
        public Nullable<long> ClusterLogLevel { get; set; }
        public Nullable<long> ClusterLogSize { get; set; }
        public string CreationClassName { get; set; }
        public Nullable<long> CrossSubnetDelay { get; set; }
        public Nullable<long> CrossSubnetThreshold { get; set; }
        public string Dedicated { get; set; }
        public Nullable<long> DefaultNetworkRole { get; set; }
        public string Description { get; set; }
        public Nullable<long> EnableSharedVolumes { get; set; }
        public Nullable<long> FixQuorum { get; set; }
        public Nullable<long> HangRecoveryAction { get; set; }
        public string IdentifyingDescriptions { get; set; }
        public Nullable<long> IgnorePersistentStateOnStartup { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<long> LogResourceControls { get; set; }
        public Nullable<long> MaxNumberOfNodes { get; set; }
        public string NameFormat { get; set; }
        public string OtherIdentifyingInfo { get; set; }
        public Nullable<long> PlumbAllCrossSubnetRoutes { get; set; }
        public string PrimaryOwnerContact { get; set; }
        public string PrimaryOwnerName { get; set; }
        public Nullable<long> QuorumArbitrationTimeMax { get; set; }
        public string QuorumPath { get; set; }
        public string QuorumType { get; set; }
        public Nullable<long> QuorumTypeValue { get; set; }
        public Nullable<long> RequestReplyTimeout { get; set; }
        public string Roles { get; set; }
        public Nullable<long> RootMemoryReserved { get; set; }
        public Nullable<long> SameSubnetDelay { get; set; }
        public Nullable<long> SameSubnetThreshold { get; set; }
        public string SecurityDescriptor { get; set; }
        public Nullable<long> SecurityLevel { get; set; }
        public string SharedVolumeCompatibleFilters { get; set; }
        public string SharedVolumeIncompatibleFilters { get; set; }
        public string SharedVolumesRoot { get; set; }
        public Nullable<long> ShutdownTimeoutInMinutes { get; set; }
        public string Status { get; set; }
        public Nullable<long> WitnessDatabaseWriteTimeout { get; set; }
        public Nullable<long> WitnessRestartInterval { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
