//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkAdapterConfiguration
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid Uid { get; set; }
        public Nullable<byte> ArpAlwaysSourceRoute { get; set; }
        public Nullable<byte> ArpUseEtherSnap { get; set; }
        public string Caption { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string DatabasePath { get; set; }
        public Nullable<byte> DeadgwDetectEnabled { get; set; }
        public string DefaultIpGateway { get; set; }
        public string DefaultTos { get; set; }
        public string DefaultTtl { get; set; }
        public string Description { get; set; }
        public string DeviceId { get; set; }
        public Nullable<byte> DhcpEnabled { get; set; }
        public string DhcpLeaseExpires { get; set; }
        public string DhcpLeaseObtained { get; set; }
        public string DhcpServer { get; set; }
        public string DnsDomain { get; set; }
        public string DnsDomainSuffixSearchOrder { get; set; }
        public Nullable<byte> DnsEnabledForWinsResolution { get; set; }
        public string DnsServerSearchOrder { get; set; }
        public Nullable<byte> DomainDnsRegistrationEnabled { get; set; }
        public Nullable<long> ForwardBufferMemory { get; set; }
        public Nullable<byte> FullDnsRegistrationEnabled { get; set; }
        public string GatewayCostMetric { get; set; }
        public string IgmpLevel { get; set; }
        public Nullable<long> IndexId { get; set; }
        public Nullable<int> InterfaceIndex { get; set; }
        public string IpAddress { get; set; }
        public Nullable<long> IpConnectionMetric { get; set; }
        public Nullable<byte> IpEnabled { get; set; }
        public Nullable<byte> IpFilterSecurityEnabled { get; set; }
        public string IpSecPermitIpProtocols { get; set; }
        public string IpSecPermitTcpPorts { get; set; }
        public string IpSecPermitUdpPorts { get; set; }
        public string IpSubnet { get; set; }
        public string IpUseZeroBroadcast { get; set; }
        public string IpxAddress { get; set; }
        public Nullable<byte> IpxEnabled { get; set; }
        public Nullable<long> IpxMediaType { get; set; }
        public string IpxNetworkNumber { get; set; }
        public string IpxVirtualNetNumber { get; set; }
        public Nullable<long> KeepAliveInterval { get; set; }
        public Nullable<long> KeepAliveTime { get; set; }
        public string MacAddress { get; set; }
        public Nullable<long> Mtu { get; set; }
        public Nullable<long> NumForwardPackets { get; set; }
        public Nullable<byte> PmtuDiscoveryEnabled { get; set; }
        public Nullable<byte> PmtubhDetectEnabled { get; set; }
        public string ServiceName { get; set; }
        public string SettingId { get; set; }
        public Nullable<long> TcpIpnetBiosOptions { get; set; }
        public Nullable<long> TcpMaxConnectRetransmissions { get; set; }
        public Nullable<long> TcpMaxDataRetransmissions { get; set; }
        public Nullable<long> TcpNumConnections { get; set; }
        public Nullable<byte> TcpUseRfc1122UrgentPointer { get; set; }
        public Nullable<int> TcpWindowSize { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<byte> WinsEnableLmhostsLookup { get; set; }
        public string WinsHostLookupFile { get; set; }
        public string WinsPrimaryServer { get; set; }
        public string WinsScopeId { get; set; }
        public string WinsSecondaryServer { get; set; }
        public string WmiDnsHostName { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
