//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkAdapters1
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid Uid { get; set; }
        public string AdapterType { get; set; }
        public Nullable<int> AdapterTypeId { get; set; }
        public Nullable<byte> AutoSense { get; set; }
        public Nullable<int> Availability { get; set; }
        public string Caption { get; set; }
        public Nullable<byte> ConfigManagerUserConfig { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string Description { get; set; }
        public string DeviceId { get; set; }
        public Nullable<long> IndexId { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<byte> Installed { get; set; }
        public Nullable<int> InterfaceIndex { get; set; }
        public string MacAddress { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<long> MaxNumberControlled { get; set; }
        public Nullable<long> MaxSpeed { get; set; }
        public string Name { get; set; }
        public string NetConnectionId { get; set; }
        public Nullable<int> NetConnectionStatus { get; set; }
        public string NetworkAddresses { get; set; }
        public string PermanentAddress { get; set; }
        public string PnpDeviceId { get; set; }
        public string ProductName { get; set; }
        public string ServiceName { get; set; }
        public Nullable<long> Speed { get; set; }
        public string Status { get; set; }
        public Nullable<int> StatusInfo { get; set; }
        public Nullable<long> TimeSinceBootOfLastChange { get; set; }
        public string SystemName { get; set; }
        public Nullable<System.DateTime> TimeOfLastReset { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
