//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkAdapter
    {
        public System.Guid DeviceNumber { get; set; }
        public string InterfaceName { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public string MacAddress { get; set; }
        public string Ipv4Addr { get; set; }
        public string BroadcastAddr { get; set; }
        public string NetMask { get; set; }
        public string Ipv6Addr { get; set; }
        public Nullable<int> Mtu { get; set; }
        public Nullable<long> RxPackets { get; set; }
        public Nullable<long> RxBytes { get; set; }
        public Nullable<long> RxErrors { get; set; }
        public Nullable<long> TxPackets { get; set; }
        public Nullable<long> TxBytes { get; set; }
        public Nullable<long> TxErrors { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
