//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office365Assessment
    {
        public System.Guid DeviceNumber { get; set; }
        public string ComputerSystemName { get; set; }
        public Nullable<byte> CpuAssessment { get; set; }
        public Nullable<byte> HarddiskAssessment { get; set; }
        public Nullable<byte> VideoMemoryAssessment { get; set; }
        public Nullable<byte> MemoryAssessment { get; set; }
        public Nullable<byte> OsAssessment { get; set; }
        public Nullable<byte> BrowserAssessment { get; set; }
        public Nullable<byte> DotNetFrameworkAssessment { get; set; }
        public Nullable<byte> OfficeSuiteAssessment { get; set; }
        public Nullable<byte> AggregateAssessment { get; set; }
        public string ReasonAggregateAssessment { get; set; }
        public Nullable<int> RecommendationAggregateAssessment { get; set; }
        public Nullable<byte> WebAppsAssessment { get; set; }
        public string ReasonWebAppsAssessment { get; set; }
        public string RecommendationWebAppsAssessment { get; set; }
        public Nullable<bool> IsWindows7OrLater { get; set; }
        public Nullable<byte> ExchangeSharepointAssessment { get; set; }
        public Nullable<int> ReasonExchangeSharepointAssessment { get; set; }
        public Nullable<int> RecommendationExchangeSharepointAssessment { get; set; }
        public Nullable<int> Office20102013Upgradability { get; set; }
    }
}
