//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office2010Assessment
    {
        public System.Guid DeviceNumber { get; set; }
        public Nullable<byte> AggregateAssessment { get; set; }
        public string ComputerSystemName { get; set; }
        public Nullable<byte> CpuAssessment { get; set; }
        public Nullable<byte> HarddiskAssessment { get; set; }
        public Nullable<byte> OsAssessment { get; set; }
        public Nullable<byte> OsUpgradeability { get; set; }
        public Nullable<byte> MemoryAssessment { get; set; }
        public string ReasonAggregateAssessment { get; set; }
        public int OfficeVersion { get; set; }
    }
}
