//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OsFamilyNameInfo1
    {
        public int PatternPriority { get; set; }
        public Nullable<byte> ProductType { get; set; }
        public Nullable<byte> VersionId { get; set; }
        public Nullable<byte> SkuId { get; set; }
        public string FamilyName { get; set; }
    }
}
