//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OsSkuInfo
    {
        public long OsSkuId { get; set; }
        public byte OsSkuFamily { get; set; }
        public byte OsSkuLevel { get; set; }
        public Nullable<bool> OsSkuIsCore { get; set; }
        public Nullable<bool> OsSkuIsN { get; set; }
        public Nullable<bool> OsSkuIsEvaluation { get; set; }
    }
}
