//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processors1
    {
        public System.Guid DeviceNumber { get; set; }
        public short Processor { get; set; }
        public string VendorId { get; set; }
        public Nullable<short> CpuFamily { get; set; }
        public Nullable<short> Model { get; set; }
        public string ModelName { get; set; }
        public Nullable<short> Stepping { get; set; }
        public Nullable<int> CpuMhz { get; set; }
        public Nullable<int> CacheSizeKb { get; set; }
        public Nullable<short> PhysicalId { get; set; }
        public Nullable<short> CoreId { get; set; }
        public Nullable<byte> AddressWidth { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
