//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processors2
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid Uid { get; set; }
        public Nullable<int> AddressWidth { get; set; }
        public Nullable<int> Architecture { get; set; }
        public Nullable<int> Availability { get; set; }
        public string Caption { get; set; }
        public Nullable<long> ConfigManagerErrorCode { get; set; }
        public Nullable<bool> ConfigManagerUserConfig { get; set; }
        public Nullable<int> CpuStatus { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<long> CurrentClockSpeed { get; set; }
        public Nullable<int> CurrentVoltage { get; set; }
        public Nullable<int> DataWidth { get; set; }
        public string Description { get; set; }
        public string DeviceId { get; set; }
        public Nullable<bool> ErrorCleared { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<long> ExtClock { get; set; }
        public Nullable<int> Family { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<long> L2CacheSize { get; set; }
        public Nullable<long> L2CacheSpeed { get; set; }
        public Nullable<int> L3CacheSize { get; set; }
        public Nullable<int> L3CacheSpeed { get; set; }
        public Nullable<long> LastErrorCode { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> LoadPercentage { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<long> MaxClockSpeed { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumberOfCores { get; set; }
        public Nullable<int> NumberOfLogicalProcessors { get; set; }
        public string OtherFamilyDescription { get; set; }
        public string PnpDeviceId { get; set; }
        public string PowerManagementCapabilities { get; set; }
        public Nullable<bool> PowerManagementSupported { get; set; }
        public string ProcessorId { get; set; }
        public Nullable<int> ProcessorType { get; set; }
        public Nullable<int> Revision { get; set; }
        public string Role { get; set; }
        public string SocketDesignation { get; set; }
        public string Status { get; set; }
        public Nullable<int> StatusInfo { get; set; }
        public string Stepping { get; set; }
        public string UniqueId { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> UpgradeMethod { get; set; }
        public string Version { get; set; }
        public Nullable<long> VoltageCaps { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
