//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processor
    {
        public System.Guid DeviceNumber { get; set; }
        public string CpuInfo { get; set; }
        public string LogicalProcessor { get; set; }
        public string EnabledCpu { get; set; }
        public string EnabledSockets { get; set; }
        public string CorePerSockets { get; set; }
        public string ProcessorModel { get; set; }
        public string ComputerModel { get; set; }
        public string ComputerId { get; set; }
        public string ComputerSerialNumber { get; set; }
        public string Version { get; set; }
        public string License { get; set; }
        public string Memory { get; set; }
        public string HyperThreading { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
