//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsUninstall
    {
        public System.Guid DeviceNumber { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string DisplayName { get; set; }
        public string DisplayVersion { get; set; }
        public string InstallDate { get; set; }
        public string InstallLocation { get; set; }
        public string ParentDisplayName { get; set; }
        public string ParentKeyName { get; set; }
        public string Publisher { get; set; }
        public Nullable<long> SystemComponent { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<long> VersionMajor { get; set; }
        public Nullable<long> VersionMinor { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
