//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCode
    {
        public string IdentifyingNumber { get; set; }
        public bool IsFull { get; set; }
        public bool IsEval { get; set; }
        public bool Is32Bit { get; set; }
        public bool Is64Bit { get; set; }
    }
}
