//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDLicensingKeyPack
    {
        public System.Guid DeviceNumber { get; set; }
        public int KeyPackId { get; set; }
        public Nullable<byte> KeyPackType { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string ProductVersion { get; set; }
        public Nullable<byte> ProductType { get; set; }
        public Nullable<long> TotalLicenses { get; set; }
        public Nullable<long> IssuedLicenses { get; set; }
        public Nullable<long> AvailableLicenses { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
