//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCDiscoveredDevice
    {
        public System.Guid DeviceNumber { get; set; }
        public Nullable<long> Active { get; set; }
        public Nullable<int> Client { get; set; }
        public string ClientVersion { get; set; }
        public string LastLogonUserDomain { get; set; }
        public string LastLogonUserName { get; set; }
        public string Name { get; set; }
        public string NetbiosName { get; set; }
        public string ResourceDomainOrWorkgroup { get; set; }
        public string OperatingSystemNameandVersion { get; set; }
        public string ResourceNames { get; set; }
        public string SMSAssignedSites { get; set; }
        public string SystemRoles { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
