//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerAssessment
    {
        public Nullable<byte> AggregateAssessment { get; set; }
        public Nullable<byte> BiosAssessment { get; set; }
        public string ComputerSystemName { get; set; }
        public Nullable<byte> CpuAssessment { get; set; }
        public System.Guid DeviceNumber { get; set; }
        public Nullable<byte> HarddiskAssessment { get; set; }
        public Nullable<long> HarddiskFreeSpaceMax { get; set; }
        public Nullable<byte> MemoryAssessment { get; set; }
        public Nullable<byte> OpticaldiskAssessment { get; set; }
        public Nullable<int> ProductType { get; set; }
        public string ReasonAggregateAssessment { get; set; }
        public Nullable<long> TotalPhysicalMemory { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
