//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsSiteSystemSummarizer
    {
        public System.Guid DeviceNumber { get; set; }
        public string SiteCode { get; set; }
        public string SiteObject { get; set; }
        public string SiteSystem { get; set; }
        public string Role { get; set; }
        public long ObjectType { get; set; }
        public Nullable<long> AvailabilityState { get; set; }
        public Nullable<long> BytesFree { get; set; }
        public Nullable<long> BytesTotal { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<System.DateTime> DownSince { get; set; }
        public Nullable<int> PercentFree { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
