//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlInstance
    {
        public System.Guid DeviceNumber { get; set; }
        public string Servicename { get; set; }
        public string InstanceName { get; set; }
        public Nullable<int> Sqlservicetype { get; set; }
        public string VersionCoalesce { get; set; }
        public string Skuname { get; set; }
        public Nullable<int> Splevel { get; set; }
        public Nullable<int> Clustered { get; set; }
        public string Instanceid { get; set; }
        public string Vsname { get; set; }
        public Nullable<long> Language { get; set; }
        public Nullable<byte> IsIntegratedsecurity { get; set; }
        public Nullable<byte> IsSingleUser { get; set; }
        public string ClrVersion { get; set; }
        public string Collation { get; set; }
        public Nullable<int> Lcid { get; set; }
        public string LicenseType { get; set; }
        public Nullable<int> NumLicenses { get; set; }
        public string ServerName { get; set; }
        public Nullable<int> SqlConnected { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
