//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySummary
    {
        public System.Guid SurveyGuid { get; set; }
        public string SurveyName { get; set; }
        public string Description { get; set; }
        public string Locale { get; set; }
    }
}
