//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageHour
    {
        public long DeviceId { get; set; }
        public long ServiceInstanceId { get; set; }
        public System.DateTime ServiceHour { get; set; }
        public int ServiceCount { get; set; }
    
        public virtual UsageDevice UsageDevice { get; set; }
        public virtual UsageServiceInstance UsageServiceInstance { get; set; }
    }
}
