//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageServiceInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsageServiceInstance()
        {
            this.UsageHours = new HashSet<UsageHour>();
            this.UsageRecords = new HashSet<UsageRecord>();
        }
    
        public long ServiceInstanceId { get; set; }
        public byte ServiceTypeId { get; set; }
        public long ServerDeviceId { get; set; }
        public string InstanceName { get; set; }
        public string SiteUrl { get; set; }
        public byte ServiceEdition { get; set; }
    
        public virtual UsageDevice UsageDevice { get; set; }
        public virtual UsageDeviceSummary UsageDeviceSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsageHour> UsageHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsageRecord> UsageRecords { get; set; }
    }
}
