//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageDeviceSummary
    {
        public long ServiceInstanceId { get; set; }
        public System.DateTime FirstEventTime { get; set; }
        public System.DateTime LastEventTime { get; set; }
        public int UserCount { get; set; }
        public int DeviceCount { get; set; }
    
        public virtual UsageServiceInstance UsageServiceInstance { get; set; }
    }
}
