//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageLogFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsageLogFile()
        {
            this.UsageLogFilesDevices = new HashSet<UsageLogFilesDevice>();
        }
    
        public long LogFileId { get; set; }
        public string LogFilePath { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public long LogFileSize { get; set; }
        public byte LogFileState { get; set; }
        public byte LogFileType { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public Nullable<System.DateTime> FirstEventTime { get; set; }
        public Nullable<System.DateTime> LastEventTime { get; set; }
        public Nullable<System.DateTime> ReservedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsageLogFilesDevice> UsageLogFilesDevices { get; set; }
    }
}
