//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsageRecord()
        {
            this.UsageRecordEvents = new HashSet<UsageRecordEvent>();
        }
    
        public long UsageId { get; set; }
        public long ServiceInstanceId { get; set; }
        public Nullable<long> ImpersonatedUserId { get; set; }
        public Nullable<long> RealUserId { get; set; }
        public Nullable<long> ClientDeviceId { get; set; }
    
        public virtual UsageDevice UsageDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsageRecordEvent> UsageRecordEvents { get; set; }
        public virtual UsageServiceInstance UsageServiceInstance { get; set; }
        public virtual UsageUser UsageUser { get; set; }
        public virtual UsageUser UsageUser1 { get; set; }
    }
}
