//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageLogFilesDevice
    {
        public long LogFileId { get; set; }
        public long ServerId { get; set; }
        public long RecordCount { get; set; }
    
        public virtual UsageDevice UsageDevice { get; set; }
        public virtual UsageLogFile UsageLogFile { get; set; }
    }
}
