//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsageDevice()
        {
            this.UsageHours = new HashSet<UsageHour>();
            this.UsageLogFilesDevices = new HashSet<UsageLogFilesDevice>();
            this.UsageRecords = new HashSet<UsageRecord>();
            this.UsageServiceInstances = new HashSet<UsageServiceInstance>();
        }
    
        public long DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string DomainName { get; set; }
        public string DeviceIp { get; set; }
        public Nullable<System.Guid> DeviceNumber { get; set; }
    
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsageHour> UsageHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsageLogFilesDevice> UsageLogFilesDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsageRecord> UsageRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsageServiceInstance> UsageServiceInstances { get; set; }
    }
}
