//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class VdiWorkloadConsolidation
    {
        public System.Guid WorkloadGuid { get; set; }
        public byte ProfileType { get; set; }
        public Nullable<int> Count { get; set; }
        public string Config { get; set; }
    }
}
