//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoController
    {
        public System.Guid DeviceNumber { get; set; }
        public System.Guid Uid { get; set; }
        public string AcceleratorCapabilities { get; set; }
        public string AdapterCompatibility { get; set; }
        public string AdapterDacType { get; set; }
        public Nullable<long> AdapterRam { get; set; }
        public Nullable<int> Availability { get; set; }
        public string CapabilityDescriptions { get; set; }
        public string Caption { get; set; }
        public Nullable<byte> ConfigManagerUserConfig { get; set; }
        public Nullable<int> CreateCollectorId { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public Nullable<long> CurrentBitsPerPixel { get; set; }
        public Nullable<long> CurrentHorizontalResolution { get; set; }
        public Nullable<long> CurrentNumberOfColors { get; set; }
        public Nullable<long> CurrentNumberOfColumns { get; set; }
        public Nullable<long> CurrentNumberOfRows { get; set; }
        public Nullable<long> CurrentRefreshRate { get; set; }
        public Nullable<int> CurrentScanMode { get; set; }
        public Nullable<long> CurrentVerticalResolution { get; set; }
        public string Description { get; set; }
        public string DeviceId { get; set; }
        public Nullable<long> DeviceSpecificPens { get; set; }
        public Nullable<long> DitherType { get; set; }
        public Nullable<System.DateTime> DriverDate { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<long> MaxMemorySupported { get; set; }
        public Nullable<long> MaxNumberControlled { get; set; }
        public Nullable<long> MaxRefreshRate { get; set; }
        public Nullable<long> MinRefreshRate { get; set; }
        public Nullable<byte> MonoChrome { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumberOfColorPlanes { get; set; }
        public Nullable<long> NumberOfVideoPages { get; set; }
        public string PnpDeviceId { get; set; }
        public string PowerManagementCapabilities { get; set; }
        public Nullable<byte> PowerManagementSupported { get; set; }
        public Nullable<int> ProtocolSupported { get; set; }
        public Nullable<long> ReservedSystemPaletteEntries { get; set; }
        public Nullable<int> StatusInfo { get; set; }
        public string SystemName { get; set; }
        public Nullable<long> SystemPaletteEntries { get; set; }
        public Nullable<System.DateTime> TimeOfLastReset { get; set; }
        public Nullable<int> UpdateCollectorId { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public Nullable<int> VideoArchitecture { get; set; }
        public Nullable<int> VideoMemoryType { get; set; }
        public Nullable<int> VideoMode { get; set; }
        public string VideoModeDescription { get; set; }
        public string VideoProcessor { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
