//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WindowsInstalledSoftwareFull
    {
        public System.Guid DeviceNumber { get; set; }
        public string Name { get; set; }
        public string Vendor { get; set; }
        public string Version { get; set; }
        public int SystemComponent { get; set; }
        public string IdentifyingNumber { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<int> InstallState { get; set; }
        public string InstallLocation { get; set; }
        public string SwidSoftwareUniqueId { get; set; }
        public string SwidSoftwareLicensorName { get; set; }
        public string SwidSoftwareLicensorId { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
