//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Windows8Assessment
    {
        public System.Guid DeviceNumber { get; set; }
        public Nullable<int> AggregateAssessment { get; set; }
        public string ReasonAggregateAssessment { get; set; }
        public Nullable<int> AggregateUpgradability { get; set; }
        public string ReasonAggregateUpgradeability { get; set; }
        public Nullable<int> GraphicsAssessment { get; set; }
        public Nullable<int> GraphicsUpgradeToMinimum { get; set; }
        public Nullable<int> CpuAddressWidth { get; set; }
        public Nullable<int> MemoryUpgradeToMinimum { get; set; }
        public Nullable<int> HarddiskFreeUpgradeToMinimum { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
