//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkLoadProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkLoadProfile()
        {
            this.WorkLoadPerfMetrics = new HashSet<WorkLoadPerfMetric>();
            this.WorkLoadDevices = new HashSet<WorkLoadDevice>();
        }
    
        public System.Guid WorkloadGuid { get; set; }
        public string WorkloadName { get; set; }
        public string Config { get; set; }
        public Nullable<System.DateTime> ConfigDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkLoadPerfMetric> WorkLoadPerfMetrics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkLoadDevice> WorkLoadDevices { get; set; }
    }
}
