//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.MapToolkit.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS2008R2Assessment
    {
        public System.Guid DeviceNumber { get; set; }
        public Nullable<byte> AggregateAssessment { get; set; }
        public Nullable<byte> AggregateUpgradeability { get; set; }
        public Nullable<byte> BiosAssessment { get; set; }
        public Nullable<byte> CpuAssessment { get; set; }
        public Nullable<byte> CpuAddressWidth { get; set; }
        public Nullable<byte> GigabitAssessment { get; set; }
        public Nullable<byte> HarddiskAssessment { get; set; }
        public Nullable<byte> HarddiskFreeSpace { get; set; }
        public Nullable<byte> HarddiskFreeUpgradeToMinimum { get; set; }
        public Nullable<byte> HarddiskFreeUpgradeToRecommended { get; set; }
        public Nullable<byte> HarddiskUpgradeToMinimum { get; set; }
        public Nullable<byte> HarddiskUpgradeToRecommended { get; set; }
        public Nullable<byte> MemoryAssessment { get; set; }
        public Nullable<byte> MemoryUpgradeToMinimum { get; set; }
        public Nullable<byte> MemoryUpgradeToRecommended { get; set; }
        public Nullable<byte> OpticaldiskAssessment { get; set; }
        public Nullable<byte> OpticaldiskUpgradeToMinimum { get; set; }
        public Nullable<byte> OpticaldiskUpgradeToRecommended { get; set; }
        public string ReasonAggregateAssessment { get; set; }
        public string ReasonAggregateUpgradeability { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
