SELECT [DeviceNumber]
      ,[AccountExpires]
      ,[ActivationRequired]
      ,CONVERT(VARCHAR, [AdDatetime]) AS AdDatetimeString
      ,[AdDnsHostName]
      ,[AdDomainName]
      ,[AdFullyQualifiedDomainName]
      ,[AdOsVersion]
      ,[AdCollector]
      ,[AdminPasswordStatus]
      ,[BiosBuildNumber]
      ,[BiosCharacteristics]
      ,[BiosCodeset]
      ,CONVERT(VARCHAR, [BiosInstallDate]) AS BiosInstallDateString
	  ,[BiosManufacturer]
      ,[BiosName]
      ,CONVERT(VARCHAR, [BiosReleaseDate]) AS BiosReleaseDateString
      ,[BiosSerialNumber]
      ,[BiosVersion]
      ,[BootDevice]
      ,[BootRomSupported]
      ,[BuildNumber]
      ,[BusType]
      ,[ChassisBootUpState]
      ,[ComputerSystemName]
      ,[ChassisTypes]
      ,[CountryCode]
      ,[CreateCollectorId]
      ,CONVERT(VARCHAR,[CreateDatetime]) AS CreateDatetimeString
      ,CONVERT(VARCHAR,[CreationDate]) AS CreationDateString
      ,[CsdVersion]
      ,[CurrentLanguage]
      ,[CurrentTimeZone]
      ,[DayLightInEffect]
      ,[Debug]
      ,[Description]
      ,[DeviceStatusScm]
      ,[DeviceStatusSnmp]
      ,[DeviceStatusWmi]
      ,[DistinguishedName]
      ,[DnsHostName]
      ,[DomainName]
      ,[DomainRole]
      ,[Drive]
      ,[EnableDaylightSavingsTime]
      ,[EnclosureManufacturer]
      ,[EnclosureSerialNumber]
      ,[EncryptionLevel]
      ,[FreePhysicalMemory]
      ,[FreeSpace]
      ,[FreeSpaceInPagingFiles]
      ,[FreeVirtualMemory]
      ,[FrontPanelResetStatus]
      ,[HotSwappable]
      ,[HostNameForVm]
      ,[IdentificationCode]
      ,[InfraredSupported]
      ,[InsertState]
      ,[InstallableLanguages]
      ,[InventoryRowversion]
      ,[InventoryWatermark]
      ,[NetworkIpAddress]
      ,[KeyboardPasswordStatus]
      ,[LanguageEdition]
      ,[LargeSystemCache]
      ,CONVERT(VARCHAR, [LastBootupTime]) AS LastBootupTimeString
      ,[LastLogonTimestamp]
      ,[LastUserLogon]
      ,[LastLoggedOnUser]
      ,CONVERT(VARCHAR, [LocalDatetime]) AS LocalDatetimeString
      ,[Locale]
      ,[Location]
      ,[LockPresent]
      ,[MaxNumberOfProcesses]
      ,[MaxProcessMemorySize]
      ,[MaximumSize]
      ,[Model]
      ,[MuiLanguages]
      ,[NetServerEnumDomainName]
      ,[NetServerEnumOsVersion]
      ,[NetworkServerModeEnabled]
      ,[NumberOfCores]
      ,[NumberOfLicensedUsers]
      ,[NumberOfLogicalProcessors]
      ,[NumberOfProcessors]
      ,[NumberOfUsers]
      ,[ObjectGuid]
      ,[OperatingSystem]
      ,[OperatingSystemServicePack]
      ,[OperatingSystemSku]
      ,[Organization]
      ,[OsArchitecture]
      ,[OsBuildType]
      ,[OsCaption]
      ,[OsCodeset]
      ,[OsEncryptionLevel]
      ,CONVERT(VARCHAR, [OsInstallDate]) AS OsInstallDateString
      ,[OsLanguage]
      ,[OsManufacturer]
      ,[OsProductSuite]
      ,[OsVersion]
      ,[PartNumber]
      ,[PartOfDomain]
      ,[PauseAfterReset]
      ,[PcSystemType]
      ,[PlusProductId]
      ,[PlusVersionNumber]
      ,[PowerOnPasswordStatus]
      ,[PowerState]
      ,[PowerSupplyState]
      ,[PrimaryBios]
      ,[PrimaryFlag]
      ,[PrimaryOwnerContact]
      ,[PrimaryOwnerName]
      ,[ProductId]
      ,[ProductType]
      ,[PwdLastSet]
      ,[QuantumLength]
      ,[QuantumType]
      ,CONVERT(VARCHAR, [RegistryDatetime]) AS RegistryDatetimeString
      ,[RegistryScanResult]
      ,[RegisteredUser]
      ,[RemainingEvaluationPeriod]
      ,[RemainingGracePeriod]
      ,[Removable]
      ,[Replaceable]
      ,[ResetCapability]
      ,[ResetCount]
      ,[ResetLimit]
      ,[Roles]
      ,CONVERT(VARCHAR, [ScmDatetime]) AS ScmDateTimeString
      ,[SecurityBreach]
      ,[SecurityStatus]
      ,[SerialNumber]
      ,[ServerName]
      ,[ServicePackMajorVersion]
      ,[ServicePackMinorVersion]
      ,[SiteName]
      ,[SmbiosAssetTag]
      ,[SmbiosBiosVersion]
      ,[SmbiosMajorVersion]
      ,[SmbiosMinorVersion]
      ,[SmbiosPresent]
      ,[SnmpManufacturerOid]
      ,[SnmpScanResult]
      ,[SshScanResult]
      ,[SuiteMask]
      ,[SupportContactDescription]
      ,[SystemDevice]
      ,[SystemDirectory]
      ,[SystemDrive]
      ,[SystemStartupDelay]
      ,[SystemType]
      ,[TotalPhysicalMemory]
      ,[TotalSwapSpaceSize]
      ,[TotalVirtualMemorySize]
      ,[TotalVisibleMemorySize]
      ,[UpdateCollectorId]
      ,CONVERT(VARCHAR, [UpdateDatetime]) AS UpdateDatetimeString
      ,[UserName]
      ,[VmFriendlyName]
      ,[WakeupType]
      ,[WindowsDirectory]
      ,[WinNetworkCollector]
      ,CONVERT(VARCHAR, [WinNetworkDatetime]) AS WinNetworkDatetimeString
      ,[WmiChassisTypes]
      ,CONVERT(VARCHAR, [WmiDatetime]) AS WmiDatetimeString
      ,[WmiDnsHostName]
      ,[WmiDomainName]
      ,[WmiProductType]
      ,[WmiOsVersion]
      ,[WmiScanResult]
      ,CONVERT(VARCHAR, [WmiScanResultDatetime]) AS WmuScanResultDatetimeString
      ,[WmiDepScanResult]
      ,CONVERT(VARCHAR, [WmiDepScanResultDatetime]) AS WmiDepScanResultDatetimeString
      ,[Workgroup]
  FROM [MAP_SampleDB].[Core_Inventory].[Devices]