SELECT [DeviceNumber]
      ,[Uid]
      ,[AdapterType]
      ,[AdapterTypeId]
      ,[AutoSense]
      ,[Availability]
      ,[Caption]
      ,[ConfigManagerUserConfig]
      ,[CreateCollectorId]
      ,CONVERT(VARCHAR, [CreateDatetime]) AS CreateDatetimeString
      ,[Description]
      ,[DeviceId]
      ,[IndexId]
      ,[InstallDate]
      ,[Installed]
      ,[InterfaceIndex]
      ,[MacAddress]
      ,[Manufacturer]
      ,[MaxNumberControlled]
      ,[MaxSpeed]
      ,[Name]
      ,[NetConnectionId]
      ,[NetConnectionStatus]
      ,[NetworkAddresses]
      ,[PermanentAddress]
      ,[PnpDeviceId]
      ,[ProductName]
      ,[ServiceName]
      ,[Speed]
      ,[Status]
      ,[StatusInfo]
      ,[TimeSinceBootOfLastChange]
      ,[SystemName]
      ,CONVERT(VARCHAR, [TimeOfLastReset]) AS TimeOfLastResetString
      ,[UpdateCollectorId]
      ,[UpdateDatetime]
  FROM [MAP_SampleDB].[Win_Inventory].[NetworkAdapters]