//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineColor
    {
        public long r { get; set; }
        public long g { get; set; }
        public long b { get; set; }
        public Nullable<long> a { get; set; }
        public string operation { get; set; }
        public Nullable<int> style_Id { get; set; }
        public int lineColor_Id { get; set; }
    
        public virtual style style { get; set; }
    }
}
