//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class metadata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public metadata()
        {
            this.management = new HashSet<management>();
            this.performance = new HashSet<performance>();
            this.processinghistory = new HashSet<processinghistory>();
            this.property = new HashSet<property>();
            this.usage = new HashSet<usage>();
        }
    
        public string operation { get; set; }
        public string schema { get; set; }
        public string schemaversion { get; set; }
        public int metadata_Id { get; set; }
        public Nullable<int> model_Id { get; set; }
        public Nullable<int> folder_Id { get; set; }
        public Nullable<int> tenant_Id { get; set; }
    
        public virtual folder folder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<management> management { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<performance> performance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processinghistory> processinghistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<property> property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usage> usage { get; set; }
        public virtual model model { get; set; }
        public virtual tenant tenant { get; set; }
    }
}
