//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class name
    {
        public string lang { get; set; }
        public string operation { get; set; }
        public string name_text { get; set; }
        public Nullable<int> model_Id { get; set; }
        public Nullable<int> folder_Id { get; set; }
        public Nullable<int> tenant_Id { get; set; }
        public int name_Id { get; set; }
    
        public virtual folder folder { get; set; }
        public virtual model model { get; set; }
        public virtual tenant tenant { get; set; }
    }
}
