//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class node
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public node()
        {
            this.documentation = new HashSet<documentation>();
            this.label = new HashSet<label>();
            this.node1 = new HashSet<node>();
            this.properties = new HashSet<properties>();
            this.style = new HashSet<style>();
        }
    
        public string identifier { get; set; }
        public string elementref { get; set; }
        public long x { get; set; }
        public long y { get; set; }
        public Nullable<long> z { get; set; }
        public long w { get; set; }
        public long h { get; set; }
        public Nullable<long> d { get; set; }
        public string type { get; set; }
        public string operation { get; set; }
        public int node_Id { get; set; }
        public Nullable<int> node_Id_0 { get; set; }
        public Nullable<int> view_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentation> documentation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<label> label { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<node> node1 { get; set; }
        public virtual node node2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<properties> properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<style> style { get; set; }
        public virtual view view { get; set; }
    }
}
