//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public property()
        {
            this.value = new HashSet<value>();
        }
    
        public string identifierref { get; set; }
        public string operation { get; set; }
        public int property_Id { get; set; }
        public Nullable<int> properties_Id { get; set; }
        public Nullable<int> metadata_Id { get; set; }
    
        public virtual metadata metadata { get; set; }
        public virtual properties properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<value> value { get; set; }
    }
}
