//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class properties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public properties()
        {
            this.property = new HashSet<property>();
        }
    
        public int properties_Id { get; set; }
        public Nullable<int> timesnap_Id { get; set; }
        public Nullable<int> element_Id { get; set; }
        public Nullable<int> relationship_Id { get; set; }
        public Nullable<int> node_Id { get; set; }
        public Nullable<int> connection_Id { get; set; }
        public Nullable<int> view_Id { get; set; }
        public Nullable<int> model_Id { get; set; }
        public Nullable<int> folder_Id { get; set; }
        public Nullable<int> tenant_Id { get; set; }
    
        public virtual connection connection { get; set; }
        public virtual element element { get; set; }
        public virtual folder folder { get; set; }
        public virtual model model { get; set; }
        public virtual node node { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<property> property { get; set; }
        public virtual relationship relationship { get; set; }
        public virtual tenant tenant { get; set; }
        public virtual timesnap timesnap { get; set; }
        public virtual view view { get; set; }
    }
}
