//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelMateEFModel9Context : DbContext
    {
        public ModelMateEFModel9Context()
            : base("name=ModelMateEFModel9Context")
        {
    	        Database.SetInitializer<ModelMateEFModel9Context>(new CreateDatabaseIfNotExists<ModelMateEFModel9Context>());
                //this.Database.Log = Console.Write;
    
                //Database.SetInitializer<SchoolDBContext>(new DropCreateDatabaseIfModelChanges<SchoolDBContext>());
                //Database.SetInitializer<SchoolDBContext>(new DropCreateDatabaseAlways<SchoolDBContext>());
                //Database.SetInitializer<SchoolDBContext>(new SchoolDBInitializer());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bendpoint> bendpoint { get; set; }
        public virtual DbSet<color> color { get; set; }
        public virtual DbSet<connection> connection { get; set; }
        public virtual DbSet<documentation> documentation { get; set; }
        public virtual DbSet<element> element { get; set; }
        public virtual DbSet<elements> elements { get; set; }
        public virtual DbSet<fillColor> fillColor { get; set; }
        public virtual DbSet<folder> folder { get; set; }
        public virtual DbSet<folders> folders { get; set; }
        public virtual DbSet<font> font { get; set; }
        public virtual DbSet<item> item { get; set; }
        public virtual DbSet<label> label { get; set; }
        public virtual DbSet<lineColor> lineColor { get; set; }
        public virtual DbSet<management> management { get; set; }
        public virtual DbSet<metadata> metadata { get; set; }
        public virtual DbSet<model> model { get; set; }
        public virtual DbSet<models> models { get; set; }
        public virtual DbSet<name> name { get; set; }
        public virtual DbSet<node> node { get; set; }
        public virtual DbSet<organization> organization { get; set; }
        public virtual DbSet<performance> performance { get; set; }
        public virtual DbSet<processinghistory> processinghistory { get; set; }
        public virtual DbSet<properties> properties { get; set; }
        public virtual DbSet<property> property { get; set; }
        public virtual DbSet<propertydef> propertydef { get; set; }
        public virtual DbSet<propertydefs> propertydefs { get; set; }
        public virtual DbSet<relationship> relationship { get; set; }
        public virtual DbSet<relationships> relationships { get; set; }
        public virtual DbSet<style> style { get; set; }
        public virtual DbSet<tenant> tenant { get; set; }
        public virtual DbSet<timesnap> timesnap { get; set; }
        public virtual DbSet<usage> usage { get; set; }
        public virtual DbSet<value> value { get; set; }
        public virtual DbSet<view> view { get; set; }
        public virtual DbSet<views> views { get; set; }
    }
}
