//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesnap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public timesnap()
        {
            this.documentation = new HashSet<documentation>();
            this.label = new HashSet<label>();
            this.properties = new HashSet<properties>();
        }
    
        public string identifier { get; set; }
        public System.DateTime timestamp { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public string operation { get; set; }
        public string schema { get; set; }
        public string schemaversion { get; set; }
        public int timesnap_Id { get; set; }
        public Nullable<int> processinghistory_Id { get; set; }
        public Nullable<int> usage_Id { get; set; }
        public Nullable<int> performance_Id { get; set; }
        public Nullable<int> management_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentation> documentation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<label> label { get; set; }
        public virtual management management { get; set; }
        public virtual performance performance { get; set; }
        public virtual processinghistory processinghistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<properties> properties { get; set; }
        public virtual usage usage { get; set; }
    }
}
