//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN.ModelMate.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class value
    {
        public string lang { get; set; }
        public string operation { get; set; }
        public string value_text { get; set; }
        public Nullable<int> property_Id { get; set; }
        public int value_Id { get; set; }
    
        public virtual property property { get; set; }
    }
}
